[package]
name = "gecko"
version = "0.1.0"
edition = "2018"

[dependencies]
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm13-0"] }
colored = "2"
convert_case = "0.5.0"
regex = "1.5.5"
codespan-reporting = "0.11.1"
